### ISSUE TITLE
script broken

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html-aam#1]
The script that transforms the tables into summary/details is broken.

**Comment by jasonkiss** [comment]
Works in master branch, but not in gh-pages / w3c.github.io snapshot where:

mapping-tables.js:3 Uncaught ReferenceError: require is not defined(anonymous function)

**Comment by jasonkiss** [comment]
Fixed in https://github.com/w3c/html-aam/commit/2cdd29f4012b262e4b32af9687167572e76ed7bf. 

Until autopublishing is working as expected, manually update the respec snapshot to call mapping-tables.js from gh-pages branch instead of master to avoid “require is not defined” error and
get the details/summary display of the mapping tables working.
