### ISSUE TITLE
Sanity check: Should 'br' really be mapped in MSAA+IA2?

### ISSUE THREAD

**Issue by joanmarie** [w3c/html-aam#118]
SSIA.

FWIW, the reason I'm curious or care at all is that I'm using HTML AAM as part of my triage to determine what missing roles we need for role parity -- and also what elements we don't need role parity for. One of my categories is "elements which don't a role because they are not mapped on any platform." I was sure `br` would be one of those, but I was wrong.

**Comment by asurkov** [comment]
Technically `<br>` element shouldn't be different than a text node having a new line character contained by `<pre>` element. So it should be exposed in accessible tree or via IAccessibleText interface, but I don't see a reason why ARIA would have it.

If ARIA wants to define text, then it needs a more generic mechanism I'd say.

**Comment by joanmarie** [comment]
I don't think ARIA should have it @asurkov. :)

But in doing my triage-via-HTML-AAM, I saw that there was a mapping for `br` for MSAA. Seems like the fix for this issue is to remove that mapping, right?

**Comment by asurkov** [comment]
On Thu, Feb 1, 2018 at 12:52 PM, joanmarie <notifications@github.com> wrote:

> I don't think ARIA should have it @asurkov <https://github.com/asurkov>.
> :)
>
ok :) mentioned just because the issue was filed as a followup of detecting
the missing ARIA roles initiative :)

But in doing my triage-via-HTML-AAM, I saw that there was a mapping for br
> for MSAA. Seems like the fix for this issue is to remove that mapping,
> right?
>

At least MSAA/IA2 mapping should match ATK - HTML:br should be exposed via
IAccessibleText. However, historically MSAA (unlike ATK) exposes accessible
objects for all text nodes, and HTML:br is not different. Not sure though,
if the spec should match the implementations in this case, cc'ing
@jasonkiss.

**Comment by jasonkiss** [comment]
While there is some chicken and egg to the status of the mappings listed in the HTML-AAM, it is a rec-track specification.

Historically, MSAA has been used to expose all sorts of things, rightly or wrongly ;)

I'm of the opinion that consistency, to the degree that it's possible, in how things are exposed across the APIs is a good thing. In that regard, it makes sense to me that `br` should not be exposed as an accessible object, but should instead, like ATK, be exposed as a '\n' character via the IAccessibleText2 interface. 

Purely in an attempt to get us closer to CR, I've made this change in d4a1976 and am closing this issue, but do reopen if you disagree.
