### ISSUE TITLE
Name calculation for img does not take in to account mapping of null alt to role=presentation

### ISSUE THREAD

**Issue by IanPouncey** [w3c/html-aam#135]
The accessible [name calculation for img](https://www.w3.org/TR/html-aam-1.0/#img-element) is potentially confusing as it does not provide the information that an image with a null alt attribute value should map to role=presentation and should, therefore, be removed from the accessibility tree (source: @stevefaulkner).

Because of this:

```
<img src="…" alt="" aria-label="An accessible name">
```

should not have an accessible name, and should not be announced by AT.

**Comment by stevefaulkner** [comment]
I think I am wrong having read this https://www.w3.org/TR/wai-aria-1.1/#conflict_resolution_presentation_none

> "Host languages elements, having implicit presentational roles for which no roles, may be applied, MUST never be exposed to in the accessibility tree. With this exception, user agents MUST always expose global WAI-ARIA states and properties to accessibility APIs. In this case, the user agent ignores the presentation role and exposes the element according to its implicit native semantics."

**Comment by scottaohara** [comment]
per the `img` naming algorithm, `aria-label` will be used over an `alt`, so the fact that `alt=""` is moot because the `aria-label` is providing the accessible name.

Additionally, Steve's quote notes that an element cannot be exposed as `presentation` if it also has an accessible name, noting it must return to the implicit native semantics. So that also works in exposing the `img` as a graphic with the accName provided by the `aria-label`.

Before I close this, do either of you feel that there should be a comment in the mapping table/disclosure widget or in the naming algorithm to call this out specifically?

**Comment by scottaohara** [comment]
After speaking with Ian and Steve offline, seems we're good with this for now.  Closing, but still welcome any comments from anyone else on clarity about this / other aspects of the spec.
