### ISSUE TITLE
HTML-AAM: determine how to map @accesskey <1 character to UIA

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#17]
_From @cyns on January 12, 2016 23:18_

_Copied from original issue: w3c/aria#183_

**Comment by boggydigital** [comment]
Not clear if that is about accesskey <1 character (?) or >1 character. Assuming it's the latter, I would suspect the issue comes from the property description: "Gets a string containing the access key character for the element." which implies it's just a single key. However the property is of value string and in my testing <div role="a" accesskey="abc">inner content</div> produced AccessKey: "abc", so it does transparently maps accesskey to AccessKey. I'll do a PR to remove the limitation...

**Comment by boggydigital** [comment]
https://github.com/w3c/html-aam/pull/125
