### ISSUE TITLE
HTML-AAM: determine best UIA mapping for @longdesc

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#22]
_From @cyns on January 12, 2016 23:44_

_Copied from original issue: w3c/aria#194_

**Comment by boggydigital** [comment]
Currently there is no UIA property that would be a good fit. We've filed internal request to have something that would work - but the current specification is factual, the property is not mapped (because there is nothing to map to). I've entertained the idea to reuse some of the general purpose description properties (FullDescription, HelpText) - but that doesn't seem to be a good fit either. 1) They're already holding valuable information in many cases and there is no room for overlap 2) This would be unnecessary painful to specify. I'll be closing this issue and when we have a change on UIA side, we'll revisit this and map to a new property.
