### ISSUE TITLE
Mapping of input type=number

### ISSUE THREAD

**Issue by JAWS-test** [w3c/html-aam#234]
I have a question about mapping input type=number:

> If implemented as a spin button, use WAI-ARIA mapping for spinbutton.
> If implemented as a text input, use WAI-ARIA mapping for textbox.

What does "implemented as a text input" mean? 

1. Is it about the incorrect display as input field in IE 11? 
2. Or is it about the display as input field with spinbutton buttons and operation in Firefox and Chrome?
 
* If the second is meant: How is assistive technology supposed to recognize that it is an input field with spinbutton functions?
* If the first is meant: How can assistive technology distinguish between HTML-input type=number and ARIA role=spinbutton? The HTML element always consists of an input field with free text input, but role=spinbutton does not have to.

See: https://github.com/w3c/aria-practices/issues/1155

**Comment by scottaohara** [comment]
the input is not always output as a control with increment/decrement capabilities.  For instance, iOS Safari still just renders an `input type=number` as a text field, as would any browser that has not implemented support / functionality for the particular type.  Not really about "incorrect" display as fallback display.

Re the bulleted questions:
* Assistive technologies know per the manner in which the browsers expose the mapping.
* ARIA alone can do things that HTML cannot.  HTML maps to the roles and semantics that make the most sense.  If alternate patterns are created that utilize the same roles, but do not match their HTML equivalents in all of their capabilities, then that can be confusing, but is not necessarily invalid.  As I noted in the linked ARIA practices thread, the UI pattern associated with that thread visually represents what would be announced as a "picker" in iOS.  That's not to say it _shouldn't_ be a `spinbutton` as that seems very appropriate as well.  But a picker is also what's used for a `select` / `listbox` like element on iOS. 

ARIA practices is a note, and provides examples of how one could use ARIA based on the ARIA specification.  But it is not normative.  From the APG description of spin buttons:

>Spinbuttons often have three components, including a text field that displays the current value, an increment button, and a decrement button. The text field is usually the only focusable component because the increment and decrement functions are keyboard accessible via arrow keys. Typically, the text field also allows users to directly edit the value. 

But, the example provided has not text input.  Again, nothing wrong with this, but again illustrates how HTML implementation of roles and allowances of ARIA do not have to match exactly in all instances.

**Comment by JAWS-test** [comment]
> but again illustrates how HTML implementation of roles and allowances of ARIA do not have to match exactly in all instances

I find this problematic because it means that assistive technology cannot know whether the spinbutton allows text input or not. So also the user of assistive technology can't know it and has to try it out.

**Comment by LJWatson** [comment]
>I find this problematic because it means that assistive technology cannot know whether the spinbutton allows text input or not. So also the user of assistive technology can't know it and has to try it out.>

It's possible to enter numbers into `<input type="number">` in all browsers. The ability to increment/decrement the numbers is layered on top of that in browsers that support it. The [MDN explainer](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) has more information about this element/type.

The screen reader queries the browser for the relevant role and uses that to inform the user whether the increment/decrement capability is available. If it isn't, as in IE11, Jaws for example announces the field as a standard "edit" field. Whereas in Blink browsers like Chrome, Brave etc. it announces as a "spin button", informing the user that they have additional functionality at their disposal.

**Comment by JAWS-test** [comment]
@LJWatson:

I'm afraid there's been a misunderstanding. The problem I have described is a completely different one:

role=spinbutton (not the HTML element) can be with or without input field. But it always has the same role, so a blind user can't know if she or he can enter text. See e.g. the wrong output with JAWS: https://github.com/FreedomScientific/VFO-standards-support/issues/271

**Comment by scottaohara** [comment]
@JAWS-test you're not wrong, there is an issue here. Whether it's with JAWS or the ARIA example I am not convinced 100% in one way or the other, though I'm leaning toward it being an issue JAWS could/should account for.   

That said, the ARIA example could also be updated to allow for a user to type characters and have the currently selected value updated to match the characters entered, like a `select` / `listbox` allow for.  That is clearly not the same functionality of a number input, but would allow for a user to effectively "type the value" or begin to type the value and hear the current selection / allowed input updated to match.

For final clarification on the topic: as you noted you filed a bug against JAWS already, and have raised the concern with the APG.  That's why I've closed this issue, as it's not an HTML AAM issue.

**Comment by mcking65** [comment]
@JAWS-test commented:
> > but again illustrates how HTML implementation of roles and allowances of ARIA do not have to match exactly in all instances
> 
> I find this problematic because it means that assistive technology cannot know whether the spinbutton allows text input or not. So also the user of assistive technology can't know it and has to try it out.

A primary purpose of ARIA is to enable people to build components that cannot be built (in an accessible way) with HTML alone. So, this disparity is by design.

In the universe of GUI components that people actually build, there are spin buttons with edit fields and spin buttons that do not have edit fields. HTML type number is only for the kind that has an edit field. ARIA enables people to build both.

All the information that an assistive technology needs to communicate how to operate a spin button is available in the accessibility tree. The AT can easily distinguish between an editable text field and an element that is not editable. If the screen reader misleads the user or leaves the user guessing unnecessarily about the element with focus, there is a gap in the screen reader design. In fairness to screen reader developers, there are many, many reasons for their design gaps and inconsistent support in such scenarios. That is one of the reasons we are developing the w3c/aria-at project to clearly establish and evaluate screen reader (and eventually other AT) support expectations for ARIA.

**Comment by mcking65** [comment]
@JAWS-test, as @scottaohara point out, you have raised the appropriate issue with Freedom Scientific. I reviewed that issue, and you have stated it perfectly.

@scottaoharacommented: 

>That said, the ARIA example could also be updated to allow for a user to type characters and have the currently selected value updated to match the characters entered

Because ARIA supports multiple types of spin buttons, we will add more examples that include an edit field. However, since the edit field is an optional aspect of the pattern, we have included this particular example that only provides increment/decrement behaviors to both illustrate its implementation and provide a test case for assistive technologies.

**Comment by scottaohara** [comment]
Thank you for the additional context @mcking65

**Comment by JAWS-test** [comment]
@mcking65 

> The AT can easily distinguish between an editable text field and an element that is not editable.

Unfortunately I don't understand the argument, because how should the AT distinguish between <code>input role=spinbutton</code> and <code>button role=spinbutton</code>? The first example would be with text input, the second not. Both are only displayed as spinbuttons in the accessibility tree, because the ARIA role overwrites the native semantics of the HTML role.
