### ISSUE TITLE
Mapping of poster

### ISSUE THREAD

**Issue by JAWS-test** [w3c/html-aam#277]
The poster attribute can be used to display an image instead of the video. The image need not be identical to an image from the video. [The poster attribute currently has no mapping](https://w3c.github.io/html-aam/#att-poster). Should it not be recognizable with AT:
* that a image is available?
* what is to be seen on the image? (for this the image would have to be able to have an alternative text, which is currently not possible in my opinion and would be an error in the HTML specification)

**Comment by scottaohara** [comment]
I tend to agree that there should be a way for information from a poster image, or the default frame a video element displays, to be relayed to AT if necessary.  However, i'm not sure i agree that the poster attribute itself requires a mapping.  

Especially without a means to provide alternative text to the displayed visual, what benefit is there in indicating that a 'poster' rather than a still frame is displayed?  If a poster-like image were the first frame of the actual video and that was displayed, we'd still have the issue of potentially important information not being relayed to users.

I think the answer here is that `video` needs a way to relay a description for the default visual display (`poster` or initial frame of the video), but not that a `poster` necessarily needs to be mapped.

**Comment by JAWS-test2** [comment]
I agree that the role "poster" is not relevant, but the information of the poster image may be relevant in rare cases and there is currently no way I know of to transmit it (unless it is written as text below the video element)

**Comment by scottaohara** [comment]
Agreed, there is no current way to relay the information of an image the `poster` attribute references.  Nor would the `poster` attribute be the mechanism to do that, much like the `src` of an `img` does not communicate the purpose of the graphic.

With that said, here's a discussion from the [W3C HTML repo about this topic](https://github.com/w3c/html/issues/1431).  Maybe some of the history that is linked to in that thread, or the recommendations this be renewed over at the [WICG Discourse](https://discourse.wicg.io/), could be where to go next?

I'm going to close this issue as there's no benefit in mapping the `poster` without being able to identify what it represents. 

Thanks
