### ISSUE TITLE
HTML Standard and html-aam interaction allows conforming images with role=img but no accessible name 

### ISSUE THREAD

**Issue by dd8** [w3c/html-aam#296]
The guidance for conformance checkers in the HTML spec says:
> A conformance checker must report the lack of an alt attribute as an error unless  ... the img element is in a figure element that satisfies the conditions described above.
https://html.spec.whatwg.org/multipage/images.html#guidance-for-conformance-checkers

But `figure` with `figcaption` doesn't affect acc name or role calculation on `img`, so images with no accessible name are conforming if they're inside a `figure` with `figcaption` 

The html-aam calcs reflect implementations - but the interaction creates problems in practice -  see https://github.com/w3c/wcag/issues/1139

**Comment by dd8** [comment]
It's not immediately obvious what the correct resolution is - should the guidance be withdrawn from the HTML Standard or should html-aam take `figcaption` into account in some way?

Using  the figcaption example from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption provides some clues:

This is quite verbose in AT since "An elephant at sunset" is voiced multiple times:
```
  <figure>
    <img src="https://cdn.pixabay.com/photo/2017/09/08/17/05/elephant-2729413__480.jpg"
         alt="Elephant at sunset">
    <figcaption>An elephant at sunset</figcaption>
</figure>

```

This is less verbose:
```
  <figure>
    <img src="https://cdn.pixabay.com/photo/2017/09/08/17/05/elephant-2729413__480.jpg"
         alt="">
    <figcaption>An elephant at sunset</figcaption>
</figure>

```

And this is least verbose in a screen reader but there's no visible caption which could disadvantage folks with low vision or COGA needs:

```
    <img src="https://cdn.pixabay.com/photo/2017/09/08/17/05/elephant-2729413__480.jpg"
         alt="Elephant at sunset">
```

And here's some data how `img` without `alt` inside `figure` is read:
https://www.powermapper.com/tests/screen-readers/labelling/img-figcaption/

**Comment by JAWS-test** [comment]
> This is less verbose:

The variant to mark the graphic within figure as layout graphic has 2 disadvantages:
* Screen reader users have no chance to save the graphic, etc., because they cannot reach it with the virtual cursor and therefore cannot use the browser context menu for graphics
* A JAWS bug in combination with layout graphics within figure will cause the figure element and its label (via figcaption) to not be output (see https://github.com/FreedomScientific/VFO-standards-support/issues/161)

**Comment by scottaohara** [comment]
i'm not convinced there's anything to change here at this time.

The thread thus far also assumes that there would only ever be a single `img` inside of a `figure`.  In reviewing client sites I've seen valid use cases where 2+ images were used/needed.  each with an alt that provides a description of the image for AT, and then a figcaption that provides a further description for why the content is deemed important.

**Comment by dd8** [comment]
The HTML Standard says figcaption can take the place of alt when the figure contains a single image. This doesn't apply when the figure contains multiple images or other content:
https://html.spec.whatwg.org/multipage/images.html#figcaption-as-alt-condition

The HTML Standard has said this for a long time and the text appeared in the W3 HTML 5.0, 5.1 and 5.2 recommendations:
https://www.w3.org/TR/2012/CR-html5-20121217/embedded-content-0.html#figcaption-as-alt-condition

This problem is this doesn't match what html-aam says or what some implementations do, so there's an inconsistency between 2 different normative standards, and implementations can conform to one or the other, but not both.

The code below is reported as conforming in https://validator.w3.org/nu due to meeting the conditions for `figcaption` as `alt`, but html-aam doesn't treat `figcaption` as `alt`:
```
<figure>
    <img src="https://cdn.pixabay.com/photo/2017/09/08/17/05/elephant-2729413__480.jpg">
    <figcaption>An elephant at sunset</figcaption>
</figure>
```

This code is reported as non-conforming due to multiple img elements. Since this is non-conforming I wouldn't expect html-aam to address it.
```
<figure>
    <img src="https://cdn.pixabay.com/photo/2017/09/08/17/05/elephant-2729413__480.jpg">
    <img src="https://cdn.pixabay.com/photo/2017/06/07/10/47/elephant-2380009_1280.jpg">
    <figcaption>Elephants</figcaption>
</figure>
```

**Comment by scottaohara** [comment]
The portion of the spec you cite is specifically about if the content of the image cannot be determined, and in such cases it is better to omit the alt (for AT, thus allowing the image's file name to possibly be announced) and rely on the figcaption to convey its purpose.  This is not "replacing the alt" as you put it, but noting that the image is provided a caption, so in this case don't throw an error due to the lack of the alt attribute.

Per the note in 4.8.4.4.14
>This is intended to avoid markup generators from being pressured into replacing the error of omitting the alt attribute with the even more egregious error of providing phony alternative text, because state-of-the-art automated conformance checkers cannot distinguish phony alternative text from correct alternative text.

All other examples of using an image in a figure show the images with appropriate alt text.

I cannot comment on what the authors of the WCAG examples assumed, and if your assertion of "Looks like these all assume figcaption provides an accessible name" is accurate or not.  What I will say is that those examples are inline with HTML's 4.8.4.4.14.  But as I said before, that section does not say the figcaption becomes the alt. In fact, that section clearly makes effort to specifically call out the distinction of the caption vs alt, per all the additional text which then goes on to note the harm in providing phony or redundant alternative text.

This then brings me back to one of your original examples:
```html
<figure>
  <img src="https://cdn.pixabay.com/photo/2017/09/08/17/05/elephant-2729413__480.jpg"
         alt="Elephant at sunset">
  <figcaption>An elephant at sunset</figcaption>
</figure>
```
The HTML spec specifically calls out that this is a bad use of figure/alt.
(per the whatwg html spec link you provided, do a find/search for the text "This example is wrong. Do not copy it." as it in parity to the above example.

As I said in my previous comment, it is best to provide a description of the image for AT, and then the figcaption is meant to be used to provide additional information that is useful to all users.

As I said before, I'm not convinced that there's anything that needs changing here.  I'm actually more convinced that there's nothing misaligned with the specs.  

I think the WCAG examples should have alt text to emphasize best practices, and not promote the idea that the allowances for when alternative text cannot be determined is how figures containing images are intended to be used.
