### ISSUE TITLE
duplicate mapping sections are showing up

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aam#360]
Something quirky must be going on with the scripts where a second mapping section for both the HTML elements and attributes are now being created.

@jnurthen or @spectranaut maybe we could look at this when we've some overlapping 'free' time?

i imagine the solution here will be to use all the aria-common scripts, and might be best to wait until https://github.com/w3c/core-aam/issues/102 is resolved?

**Comment by spectranaut** [comment]
Wow this is very odd... and since I'm looking at the same code for core-aam, I'm happy to take a look here too!

**Comment by scottaohara** [comment]
much appreciated @spectranaut

**Comment by spectranaut** [comment]
Ok, so I looked into it! It turns out [`mappingTables`](https://github.com/w3c/html-aam/blob/gh-pages/script/mapping-tables.js#L91) is called twice: once when the js file is loaded (you can see the code at the top of the file, related to respec events, which are no longer supported, according to the discussion here: https://github.com/w3c/html-aam/blob/gh-pages/script/mapping-tables.js#L91), and once during the respec [`preprocessing`](https://github.com/w3c/html-aam/blob/6da7e1d0e1020b8da7f63db6a9bb5719467051e9/index.html#L97).

I'm removing the onload running of mappingTables in the mapping-tables.js file in this pr over at core-aam: https://github.com/w3c/core-aam/pull/105

These two files should be the same file, currently they are not, mostly do to weird code formatting differences as far as I can tell. Should we wait for the other PR to land and then copy the file here?

**Comment by scottaohara** [comment]
yeah i'm fine with waiting on this.   to be fair, no one has said anything... 

if i'm looking at the head of this spec correctly, we really should be just calling all the scripts from aria-common instead of copying them here.  i think the forking of the scripts happened when HTML AAM was part of w3c's html group and then the web apps group... but now that it's back in the ARIA WG we _should_ have access to aria-common again?

... so yeh.  long way of saying i'm fine with waiting.  we can then try to just reference the common scripts instead of copying them here.  and if that doesn't work, then copy them over.

**Comment by scottaohara** [comment]
this was fixed and was actually due to some errant markup.  closing
