### ISSUE TITLE
Add mappings for proposed <search> element

### ISSUE THREAD

**Issue by domenic** [w3c/html-aam#369]
In https://github.com/whatwg/html/pull/7320, we are working to add a `<search>` element to HTML. It would be best if there was a pull request ready against html-aam (and html-aria) containing the appropriate stuff for it, so that we could merge all three pull requests around the same time.

Let me know if I can help with this!

**Comment by scottaohara** [comment]
Thanks @domenic.  I actually started on the PR for this back in November. #355.  Since the PR for HTML is moving forward, this PR is ready as well.

I imagine I we can reference the HTML AAM PR via [the existing chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1294294)?  Or should I be filing a separate issue?

Similar question for gecko and webkit issues?

**Comment by domenic** [comment]
Oh, perfect! And yes, bundling that together in the implementation bugs makes sense. Thanks!
