### ISSUE TITLE
Input type="image" - Accessible name computation

### ISSUE THREAD

**Issue by giacomo-petri** [w3c/html-aam#414]
Hi everyone,

the ACT Rules Community Group is improving an atomic rule to ensure image button has non-empty accessible name (https://deploy-preview-103--wai-wcag-act-rules.netlify.app/standards-guidelines/act/rules/59796f/).

We're discussing this topic in:
- https://github.com/act-rules/act-rules.github.io/issues/1861
- https://github.com/act-rules/act-rules.github.io/pull/1865

We're a bit concerned about how technologies (both browsers and AT) render/expose inconsistently elements that support the alt attribute, in particular input type="image" (but also img and area), especially with particular combination of attributes set (e.g. empty alt and non-empty title, empty aria-label and non-empty title, etc.).

In addition, following the [4.3.2 input type="image" Accessible Description Computation](https://www.w3.org/TR/html-aam-1.0/#input-type-image-accessible-name-computation), from steps 2  the alt attribute should be used as accessible name if present, from step 3 the title attribute should be used as accessible name if present. However, step 4  states "if the previous steps do not yield a usable text string" where it's not clear if an empty string should count as a "usable text string" or not.

We would have your opinion on what the "good" way should be to write our rule accordingly.

We've also created a html file containing the entire list of examples for every element that supports alt (img, input type="image" and area) with the combination of title and other properties (title + empty alt, title + empty aria-label and title + empty aria-labelledby). We've added valid and invalid images due to different behaviour with Firefox:
- empty alt (alt="") and non-empty title is behaving consistently both with loaded and non-loaded image
- empty aria-label (aria-label="") and empty aria-labelledby (aria-labelledby="") are behaving inconsistently

Please, let us know your thoughts.

Thanks,
Giacomo

[img-inputimg-area-examples.zip](https://github.com/w3c/html-aam/files/8930974/img-inputimg-area-examples.zip)

**Comment by JAWS-test** [comment]
See https://github.com/w3c/html-aam/pull/322 and https://github.com/w3c/accname/issues/27

**Comment by Jym77** [comment]
@JAWS-test these issue/PR relate to `<img>` elements, where (since #322 ), it has indeed been made explicite that empty `alt` stops the process.

The current question is about `<input type="image">` elements where such precision is lacking and we still have the "if the previous steps do not yield a usable text string" phrasing that was deemed ambiguous for `<img>` pre-#322.

From your comment, I understand that the intention is the same, i.e. that `<input type="image" alt="" title="Hello">` should have no name. Note that contrarily to `<img>` elements, empty `alt` does **not** give a presentational role to `<input type="image">`.

If the intention is to use `alt` on `<input type="image">` even if empty, I think we should make similar clarification as what was done on `<img>` in #322.

**Comment by jnurthen** [comment]
we should clarify what a "usable text string" means

**Comment by scottaohara** [comment]
@Jym77 @JAWS-test I realize they're both elements that use `alt`... but why are we confusing an element that is exposed as an image or as presentation with an element that is always exposed as an interactive element (button) and thus is never meant to be treated as presentation?    

The `input type=image` and `img` elements have separate naming algorithms because while the `alt` attribute overlaps, they're two very different things.

yes @jnurthen we should clarify what "usable text string" means (or just replace it with a better understood term).  This was written in before my time working on the spec - but this was always understood to me to be a non-empty string.  e.g., `aria-label=""` or `aria-label="  "` are both not usable text strings as they produce no name. edit: related - https://github.com/w3c/html-aam/issues/238

For `input type=image` what likely should happen is if there is an `alt=""` and `title=""` is what Safari does and render the fallback text (they chose "submit" as the localized text string).  chrome and firefox are not rendering the fallback text if the `alt` is set to the empty string and there's no other labeling mechanism.  That seems a mistake.

**Comment by Jym77** [comment]
@scottaohara Thanks for the clarification!

**Comment by giacomo-petri** [comment]
@scottaohara @Jym77,

thanks for your inputs and clarifications.

About:
> yes @jnurthen we should clarify what "usable text string" means (or just replace it with a better understood term). This was written in before my time working on the spec - but this was always understood to me to be a non-empty string. e.g., aria-label="" or aria-label=" " are both not usable text strings as they produce no name.

I've always understood the API mapping as an ordered list of points (checklist), in which once a specific point is satisfied, next points can be skipped.

In [HTML Accessibility API Mappings 1.0](https://www.w3.org/TR/html-aam-1.0/#input-type-image-accessible-name-computation) first point states:
> 1. If the control has an [aria-label](https://www.w3.org/TR/wai-aria-1.2/#aria-label) or an [aria-labelledby](https://www.w3.org/TR/wai-aria-1.2/#aria-labelledby) attribute the [accessible name](https://www.w3.org/TR/accname-1.2/#dfn-accessible-name) is to be calculated using the algorithm defined in [Accessible Name and Description: Computation and API Mappings](https://www.w3.org/TR/accname-1.2/).

Opening [Accessible Name and Description: Computation and API Mappings](https://www.w3.org/TR/accname-1.2/), aria-label="" or aria-label=" " scenarios are clearly explained
> C. Otherwise, if computing a [name](https://www.w3.org/TR/accname-1.2/#dfn-accessible-name), and if the current node has an aria-label [attribute](https://www.w3.org/TR/accname-1.2/#dfn-attribute) whose value is not the empty string, nor, when trimmed of white space, is not the empty string:
    - If traversal of the current node is due to recursion and the current node is an embedded control as defined in step 2E, ignore aria-label and skip to rule 2E.
    - Otherwise, return the value of aria-label.

Consequently, if aria-label="" or aria-label=" ", per algorithm I should move to the second point, that is:
> 2. Otherwise use alt attribute.

In `<img src="..." alt="" title="non-empty-string">`, based on my initial assumption, I wouldn't move to point 4 to determine if previous points yield a usable text string; the alt attribute is present, even if it's empty, and I would stop my analysis here, assuming the accessible name is empty.
I've always understood the label "Otherwise if the previous steps do not yield a usable text string" as a sort of fallback, if none of the previous points were satisfied instead of a "final" check to determine if previous points result in a "usable text string".

**Comment by scottaohara** [comment]
@giacomo-petri as mentioned, we can get this clarified.  but i would point to the fact that the `img` element specifically calls out that the `alt` be used "even if its value is the empty string." where as `input type=image` was not updated to say this.

The only thing I think there needs to be some WG alignment on is whether `alt=" "` and `alt=""` should both be treated the same, similarly to aria-label.  I don't believe they are treated the same right now.

Regarding:
>I've always understood the label "Otherwise if the previous steps do not yield a usable text string" as a sort of fallback...

i can see why you think that.  In many cases it is simply stating that if none of the above checks returned a usable accName, then there isn't one.

However, again, `input type=image` has some different language in that it has two points that use this language:

>* Otherwise if the previous steps do not yield a usable text string, the [accessible name](https://www.w3.org/TR/accname-1.2/#dfn-accessible-name) is a localized string of the word "Submit Query".
>* If none of the above yield a usable text string there is no [accessible name](https://www.w3.org/TR/accname-1.2/#dfn-accessible-name).


Per my previous comment, if both `alt=""` and `title=""` were used (aside: who the heck is doing this outside of people writing automated tests? - not saying this has never happened. just... jeez) the first of the two bullets would be reached and browsers SHOULD be returning a localized text string as the fallback text. So the last bullet indicating there was no accName would ideally never be reached for this element.  Safari is the only browser mostly doing this right now, but they do not do it if `alt=" "` (which is why i think there needs to be some discussion on why browsers would use that as an accName for `alt` but not for `aria-label`... circling back to needing to clarify 'usable text string').

**Comment by Jym77** [comment]
> aside: who the heck is doing this outside of people writing automated tests? - not saying this has never happened. just... jeez

I'm regularly looking at customer code… The things they do… 🙈 
(this kind of stuff typically happens in poorly coded templating of components)

**Comment by giacomo-petri** [comment]
I agree with all you have said.

What puzzles me is that for each Accessible Name and Description Computation, conditions behave as 
```
if (condition) { ... }   
else if (condition) { ... }  
...  
else { ... } 
```

This is the unique case where this scenario does not apply and point 4 must be reviewed even if point 2 and 3 are satisfied.
Might be an option to include the "usable text string" condition within point 2 and 3 (being consistent with other elements structure).

**Comment by scottaohara** [comment]
@Jym77 yeh... the ridiculousness i'm sure we've all seen.  that was meant more as a text equivalent of a face palm accompanied with a sigh and a shoulder shrug that go on for days.  this is why we can't have nice things...

@giacomo-petri it's not just this element.  `summary`, `input type=button|submit|reset`, for example, are also their own uniqueness as well where there is some looking back at previous steps that need to happen...   

really all of this needs to be re-looked at (and has been a todo of mine for quite some time now).   it'd be nice if i could spend all my time just doing this stuff, tbh.  but, reality...

**Comment by scottaohara** [comment]
oh, another thing here that isn't spec'd (because it's not officially allowed in HTML) but DOES produce an accessible name for `input type=image` is that if you give it a `value`, the value of that attribute can be used as the accName for the element as well... 

so that's fun.

**Comment by giacomo-petri** [comment]
I was not aware about that...

I've just tested it and the value attribute takes priority over the title attribute on both on Chrome and Firefox:
`<input type="image" src="test.png" title="title-string" value="value-string">`
returns "value-string" as accessible name.

In Safari instead 
`<input type="image" src="test.png" title="title-string" value="value-string">`
returns "title-string" as accessible name.

🤷 🤦

**Comment by scottaohara** [comment]
Pulling in the notes from @eps1lon so they can be considered as part of this issue:

1. > 2. Otherwise use alt attribute. 3. Otherwise use title attribute.

   Is the "otherwise" in point 3 similar to 5.1.1 where we have 
   > If the accessible name is still empty, then: use the control's title attribute.

   ? 
   Right now I can see no consistent language regarding these steps. It seems to me that every step only applies if the previous steps did not produce a name. But sometimes we have this explicitly mentioned and sometimes not.
2. >  the accessible name is a localized string of the word "Submit Query".

   This is followed by "If none of the above yield a usable text string there is no accessible name.". So  this localization could produce  an empty string? Wouldn't it be better to produce an accessible name in a foreign language rather than no name at all?
3. By spec this element cannot be labelled via `<label>`.
  However, a web-platform-test currently test this (https://github.com/web-platform-tests/wpt/blob/677c57c0e8816b0892cc3ae1c2772189b1bdcf65/accname/name_test_case_616-manual.html#L64-L65). Chrome 84 also allows labelling `<input type="image" />`. Should this test be removed or the spec updated to match implementations?

**Comment by hs85jeong** [comment]
We are currently working on a modification in [Chromium](https://chromium-review.googlesource.com/c/chromium/src/+/4700003), where for <input type=image> if the alt attribute has empty string, we will use the 'title' attribute instead.

**Comment by scottaohara** [comment]
thank you @hs85jeong
