### ISSUE TITLE
Small discrepancies in wording of elements whose role depends on  a name.

### ISSUE THREAD

**Issue by Jym77** [w3c/html-aam#453]
The [`form` element](https://w3c.github.io/html-aam/#el-form) is always mapped to the `form` role, with a comment stating
> If a `form` has no accessible name, do not expose the element as a landmark.

This contrasts with the [`aside`](https://w3c.github.io/html-aam/#el-aside) and [`section`](https://w3c.github.io/html-aam/#el-section) elements, whose mapping states:
> `region` role if the `section` element has an accessible name. Otherwise, the `generic` role.

I feel these actually mean the same thing. On top of the wording discrepancy, nameless `form` currently map to no role (rather than `generic` which look like the correct role as far as I understand).

---
The Core AAM is also having notes about the presence of name. For [`form`](https://w3c.github.io/core-aam/#role-map-form-nameless) and [`region`](https://w3c.github.io/core-aam/#role-map-region-nameless) roles, there are two entries (with or without name); but for [`complementary`](https://w3c.github.io/core-aam/#role-map-complementary), there is only one entry and the presence of name is not taken into account.

I am not sure if this impact the way the HTML AAM is written; in any case, the single out case is not the same in both documents which sounds weird…

---
Also, the HTML AAM mapping of `form` does link to both Core AAM mappings of `form` (with name in the `[wai-aria-1.2]` mapping, without name in the Comment), while the one for `section` only links to the Core AAM mapping of `region` with a name.

---
Possibly related but a bit different, the [`li`](https://w3c.github.io/html-aam/#el-li) element is also having a mapping plus a comment changing that mapping in some cases. This comment does make the `generic` role explicit, so it is only splitting the mapping in two places.

**Comment by scottaohara** [comment]
Hi @Jym77, there's a lot here. I'll go bit by bit...

re: the initial questioning of why there is a difference between `form` vs `aside` and `section`, no, the different wordings do not mean the same thing.  Form was discussed and updated to always map to a form role, but only if named would that form role be exposed as a landmark.  Here are some related core aam issues around this topic:

https://github.com/w3c/core-aam/issues/100
https://github.com/w3c/core-aam/issues/11

Per these changes, the intent was so that a nameless form would specifically not be generic, _but_ it would be up to AT whether or not they wanted to expose the role at all - much like how `fieldset` / `role=group` are exposed as groups in the browser's a11y tree, but AT will generally not explicitly announce their presence if they have no name.

There is some awkward wording/looping with the core aam spec on this now - as brought up here: https://github.com/w3c/core-aam/issues/159 (just transferred this to core aam from aria where it was originally filed).  So there is a fix that needs to be made.  Essentially this observation is highlighting the need to fix that existing issue.

---

>The Core AAM is also having notes about the presence of name. For [form](https://w3c.github.io/core-aam/#role-map-form-nameless) and [region](https://w3c.github.io/core-aam/#role-map-region-nameless) roles, there are two entries (with or without name); but for [complementary](https://w3c.github.io/core-aam/#role-map-complementary), there is only one entry and the presence of name is not taken into account.

Yes, this is also different on purpose.  HTML's aside element has more instances of where it should semantically be used than ARIA's complementary landmark. So sometimes the aside element should be exposed as a complementary (with or without a name) and sometimes it should be treated as generic per its other valid use cases per HTML.  Where as form (as already mentioned above) should always be exposed as a form - but whether it's named or not will determine if it's also a landmark, so that mapping is different based on its name.  Finally, region roles are always landmarks, but can be problematic if not named - so this role (regardless of it being an implicit role of section, or an explicit role=region) should be ignored and fall back to the element's implicit role (or generic) if there's no accName.  

---

>Also, the HTML AAM mapping of form does link to both Core AAM mappings of form (with name in the [wai-aria-1.2] mapping, without name in the Comment), while the one for section only links to the Core AAM mapping of region with a name.

correct, it wouldn't make sense for the section element to link to the region role without a name, as that'd just create a loop back to the section element in HTML AAM.  But as mentioned above, form's mappings need adjustments so that this infinite loop doesn't exist for form.

---

>Possibly related but a bit different, the [li](https://w3c.github.io/html-aam/#el-li) element is also having a mapping plus a comment changing that mapping in some cases. This comment does make the generic role explicit, so it is only splitting the mapping in two places.

Yup, this is the precursor to other similar changes which will be added to other elements where if developers don't use them correctly per the requirements of the HTML spec, then they will become generics.  More to come on that...

**Comment by Jym77** [comment]
Thanks for the detailed answer (and the archaeology). I'm getting a better understanding on how this interact.

* An `<aside>` element may or not be a complementary region (from [WHATWG specs](https://html.spec.whatwg.org/multipage/sections.html#the-aside-element), the first example is a complementary region but the second is not), and the way we guess that is by the presence of a name (HTML AAM). When it is a complementary region, it has a role of `complementary`, which inherits from `landmark`, and is treated as a "landmark" (whatever that means for them) by all UA/AT (Core AAM). However, if authors are sure of what they do with a `<div role="complementary">`, we trust them and use a nameless complementary (so no special case for nameless in the Core AAM).
* A `<form>` element must always be treated as a "form" (whatever that means for them) by UA/AT (I guess, making interactions work). It should, however, not always be treated as a "landmark" by them, depending on the presence of a name. Some UA/AT have different concepts for "form" and "landmark", while for ARIA `form` role always inherit from `landmark`. Treating the `<form>` element as a `generic` role would break stuff (e.g. user interaction), so it is not mapped the same way.
* A `<section>` element may be structural (and then use the `generic` role) or semantic (and use the `region` role), we also guess that based on the presence of a name (HTML AAM). We also want to classify `<div role="region">` as structural regions, not semantic ones, so there is a special case in the Core AAM for that.

I was probably focusing too much on ARIA roles where the `form` role is a `landmark` role and struggling to figure out what it would mean for something to be a form without being a landmark. Makes more sense now 👍 

Closing this 😃
