### ISSUE TITLE
Should this pending `section > h1–h6` style change have an impact on HTML-AAM mappings for accessibility 

### ISSUE THREAD

**Issue by cookiecrook** [w3c/html-aam#547]
Should this pending `section > h1–h6` style change have an impact on HTML-AAM mappings for accessibility 

- https://github.com/whatwg/html/issues/7867

**Comment by scottaohara** [comment]
naw, that change actually aligns to the fact that there was no a11y change when nesting headings like that - but visually the browsers had made that change per the outline algorithm that was never implemented.

so no a11y change, since the visuals are now being corrected to match the heading levels, as opposed to implying a change that browsers only ever made visually.
