### ISSUE TITLE
HTML-AAM: Text vs Group mapping and accessible object behaviour in UIA

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html-aam#58]
_From @jasonkiss on September 28, 2016 2:32_

In the notes prefacing the role mapping table, it says the following about UIA:

> Elements mapped to the Text Control Type are not generally represented as accessible objects in the accessibility tree, but are just part of the Text Control Pattern implemented for the whole HTML document. However, if they have any `aria-` attributes or an explicit `tabindex` specified, elements mapped to the Text Control Type will be represented as accessible objects in the accessibility tree.
1. `div` and `span` are indicated in the HTML-AAM as mapping to the Group Control Type, but in Edge14 they are initially mapped to the Text Control Type, and only become accessible objects of the Group Control Type if they have `tabindex` or `aria-*`.
2. `p` is indicated in the AAM as mapping to Text, and it keeps the Text Control Type when it becomes an accessible object. Shouldn’t it match the Edge14 behaviour for `div` and `span`?
3. Similar questions about best UIA mappings and accessible object behaviour exist for `pre`, `q`, `sub`, `sup`, `strong` and others. 

I think it makes sense to document this type of Text vs Group mapping and accessible object behaviour for these various text level semantic elements, and `div` and `span`. This could go as additional detail on that note before the mapping table, and/or maybe  as a brief note on each element's entry in the table?

@cyns, any thoughts?

_Copied from original issue: w3c/aria#437_

**Comment by boggydigital** [comment]
Here are some thoughts.

In general when mapping HTML elements to UIA elements (currently) we only create corresponding notes for the "interesting" ones and the definition is fairly broad:

- Elements that have any ARIA attributes (including role)
- Interactive elements (controls, tabindex)
- Elements that have click handlers in the ancestry chain (to support DOM events propagation and bubbling, when invoked through UIA)
- Anonymous text blocks and inlines to allow full content fidelity

This behaviour is something that might change in the future, when we'll need to address some of the gaps in this implementation - e.g. the fact we need to expose some nodes due to Core-AAM requirements (references) or the need to expose more meta data. There are no concrete plans I can announce here right now, but we are moving in that direction. Moreover, going forward instead of not including elements into UIA tree at all, we can use UIA internal views such as "raw", "control", "content" trees and include everything into "raw" tree, interactive elements into "control" tree and interesting content elements into "content". It would be absolutely worth specifying when we have a clear design, as this will be very UIA specific, but still in my opinion valuable.

Now on the specific elements mapping and text elements I don't see an issue here. Currently div/span elements are exposed as ControlType: Group and everything else that has strong text semantics - as a ControlType: Text (e.g. p, mark, pre). Now I don't think additional infromation on that would add any value - and the correct mappings are already available.

Closing for now and we can revisit if our approach to tree construction changes.
